ansible/docker_image_push.yml, ansible/inventory/env/group_vars/all.yml, ansible/inventory/env/group_vars/env.yml
=> ml-project-service

Jenkinsfile
update in jenkins files for ml-project-service
=> update in jenkins files for ml-project-service

generics/middleware/authenticator.js
changes in authenticator for template/details api
=> Authenticator condition updated

module/userProjects/helper.js
Condition and response changes in userProjects helper. API- userProjects/add
=> Condition and response changes in userProjects helper

controllers/v1/programs.js, databaseQueries/programs.js, models/programs.js, module/userProjects/helper.js
multiple program getting created problem- Resolve
=> multiple program getting created problem- Resolve

module/userProjects/helper.js
changed from userName to firstName and lastName
=> changed from userName to firstName and lastName

module/userProjects/helper.js
=> Fixing reissue certificate

module/userProjects/helper.js
added only first name in validation
=> added only first name in validation

module/userProjects/helper.js
=> Debug ED-1078

module/userProjects/helper.js
=> removed console log

app.js, controllers/v1/project/templates.js, generics/constants/endpoints.js, generics/services/core.js, module/project/templates/helper.js, module/userProjects/helper.js
fixed non targeted to targeted project issue
=> fixed non targeted to targeted project issue

.github/pull_request_template.md
=> Added PR checklist

models/programs.js, module/userProjects/helper.js
=> change added to not join old programs internally

models/programUsers.js, module/userProjects/helper.js
=> passing consentShared = true for internal calls

module/userProjects/helper.js
=> change added to pass userRoleInformation instead entire body data

module/project/templates/helper.js
=> Bug Fix: ProjectId is not getting passed fixed in dev and staging

generics/services/survey.js, module/userProjects/helper.js
=> Bug fix catching error if no entity data found

release-notes/6.0.0.md
=> added release note

generics/services/core.js, models/solutions.js, module/solutions/helper.js, module/userProjects/helper.js
=> Change to create project from private solution

module/userProjects/helper.js
=> 6.0.0 qa fix

module/userProjects/helper.js
=> Fix ED-2556

generics/constants/api-responses.js, module/userProjects/helper.js
=> Added Long Term fix for NVSK

generics/services/users.js, module/userProjects/helper.js
=> Added encEmail delete

generics/constants/api-responses.js, generics/helpers/utils.js, module/entities/helper.js, module/userProjects/helper.js, release-notes/7.0.0.md
=> Fix: Prod Obervation led imp with task level obs fix

module/userProjects/helper.js
=> worked on validation for req  body and db userlocation data

Dockerfile, generics/helpers/utils.js, generics/middleware/authenticator.js, generics/middleware/validator/index.js, module/certificateValidations/helper.js, module/library/categories/helper.js, module/project/templateTasks/helper.js, module/project/templates/helper.js, module/reports/helper.js, module/userProjects/helper.js, package.json, release-notes/8.0.0.md, routes/index.js
=> Security fixes

Dockerfile
=> upgrading node from 12 to 18

controllers/v1/userProjects.js, generics/middleware/authenticator.js
=> feat:cosmetic change usersProject/userProject to userProject/project

migrations/deleteDuplicateRecordsScript/Readme.md, migrations/deleteDuplicateRecordsScript/deleteDuplicateRecords.js
=> migration script added
